"""趋势结构引擎。

阶段 0–6：标准序列、拐点、线段、趋势线、趋势区间、生命周期，以及离线 HTML 报告。
"""

from analysis.structure.boundaries import (
    ROLE_RESISTANCE,
    ROLE_SUPPORT,
    STATUS_BROKEN,
    STATUS_CANDIDATE,
    STATUS_EXPIRED,
    STATUS_REJECTED,
    STATUS_VALIDATED,
    Boundary,
    BoundaryResult,
    build_boundaries,
    format_boundaries,
)
from analysis.structure.lifecycle import (
    EVENT_BREAKOUT,
    EVENT_EXPIRED,
    EVENT_VALIDATED,
    LifecycleResult,
    StructureEvent,
    build_lifecycle,
    format_events,
)
from analysis.structure.config import (
    BAR_INTERVALS,
    LONG,
    MID,
    PARAM_VERSION,
    PRICE_AXIS_LOG,
    PRICE_AXIS_UNIFORM,
    PRICE_BASIS_CLOSE,
    SCALE_NAMES,
    SHORT,
    StructureParams,
    default_params,
)
from analysis.structure.pivots import (
    Pivot,
    PivotDetector,
    PivotResult,
    TemporaryExtreme,
    detect_pivots,
    format_trace,
)
from analysis.structure.segments import (
    DIRECTION_DOWN,
    DIRECTION_FLAT,
    DIRECTION_UP,
    Segment,
    SegmentResult,
    TemporarySegment,
    build_segments,
    format_segments,
)
from analysis.structure.series import (
    IDENTITY_FILENAME,
    NonPositivePriceError,
    StandardSeries,
    build_series,
    result_directory,
    write_series_identity,
)
from analysis.structure.volatility import compute_volatility, reversal_threshold
from analysis.structure.html_report import render_report, write_result
from analysis.structure.snapshot import (
    build_snapshot,
    normalize_visible_scales,
    resolve_requested_window,
)
from analysis.structure.view_model import (
    READING_NOTE,
    SCALE_DEFINITION_NOTE,
    build_view_model,
    display_snapshot,
    price_axis_distance,
    price_on_line,
)
from analysis.structure.zones import (
    LABEL_CHANNEL,
    LABEL_CONVERGENCE,
    LABEL_OTHER,
    LABEL_SIDEWAYS,
    Zone,
    ZoneOverlap,
    ZoneResult,
    build_zones,
    format_zones,
)

__all__ = [
    "BAR_INTERVALS",
    "DIRECTION_DOWN",
    "DIRECTION_FLAT",
    "DIRECTION_UP",
    "EVENT_BREAKOUT",
    "EVENT_EXPIRED",
    "EVENT_VALIDATED",
    "IDENTITY_FILENAME",
    "LABEL_CHANNEL",
    "LABEL_CONVERGENCE",
    "LABEL_OTHER",
    "LABEL_SIDEWAYS",
    "LifecycleResult",
    "LONG",
    "MID",
    "Boundary",
    "BoundaryResult",
    "PARAM_VERSION",
    "PRICE_AXIS_LOG",
    "PRICE_AXIS_UNIFORM",
    "PRICE_BASIS_CLOSE",
    "ROLE_RESISTANCE",
    "ROLE_SUPPORT",
    "SCALE_NAMES",
    "SHORT",
    "STATUS_BROKEN",
    "STATUS_CANDIDATE",
    "STATUS_EXPIRED",
    "STATUS_REJECTED",
    "STATUS_VALIDATED",
    "StructureEvent",
    "NonPositivePriceError",
    "Pivot",
    "PivotDetector",
    "PivotResult",
    "Segment",
    "SegmentResult",
    "StandardSeries",
    "StructureParams",
    "TemporaryExtreme",
    "TemporarySegment",
    "Zone",
    "ZoneOverlap",
    "ZoneResult",
    "READING_NOTE",
    "SCALE_DEFINITION_NOTE",
    "build_boundaries",
    "build_snapshot",
    "build_view_model",
    "build_lifecycle",
    "build_segments",
    "build_series",
    "compute_volatility",
    "default_params",
    "detect_pivots",
    "display_snapshot",
    "format_boundaries",
    "format_events",
    "format_segments",
    "format_trace",
    "format_zones",
    "normalize_visible_scales",
    "price_axis_distance",
    "price_on_line",
    "render_report",
    "resolve_requested_window",
    "result_directory",
    "reversal_threshold",
    "write_result",
    "write_series_identity",
    "build_zones",
]
